window.addEventListener('load', (event) => {
    const params = (new URL(document.location)).searchParams;
    const topbar1 = params.get('topbar1');
    const title = params.get('title');
    const topbar2 = params.get('topbar2');
    const logoimg = params.get('logoimg');
    const bannerimg1 = params.get('bannerimg1');
    const headimg = params.get('headimg');
    const about = params.get('about');
    const revs1_1 = params.get('revs1_1');
    const revs1_2 = params.get('revs1_2');
    const food1 = params.get('food1');
    const food2 = params.get('food2');
    const food3 = params.get('food3');
    const food4 = params.get('food4');
    const menu1 = params.get('menu1');
    const mtext1 = params.get('mtext1');
    const mprice1 = params.get('mprice1');
    const menu2 = params.get('menu2');
    const mtext2 = params.get('mtext2');
    const mprice2 = params.get('mprice2');
    const menu3 = params.get('menu3');
    const mtext3 = params.get('mtext3');
    const mprice3 = params.get('mprice3');
    const menu4 = params.get('menu4');
    const mtext4 = params.get('mtext4');
    const mprice4 = params.get('mprice4');
    const image1 = params.get('image1');
    const image2 = params.get('image2');
    const image3 = params.get('image3');
    const image4 = params.get('image4');
    const image5 = params.get('image5');
    const image6 = params.get('image6');
    const image7 = params.get('image7');
    const image8 = params.get('image8');
    const mem1 = params.get('mem1');
    const memimg1 = params.get('memimg1');
    const mem2 = params.get('mem2');
    const memimg2 = params.get('memimg2');
    const mem3 = params.get('mem3');
    const memimg3 = params.get('memimg3');
    const mem4 = params.get('mem4');
    const memimg4 = params.get('memimg4');
    const mem5 = params.get('mem5');
    const memimg5 = params.get('memimg5');
    const mem6 = params.get('mem6');
    const memimg6 = params.get('memimg6');
    const mem7 = params.get('mem7');
    const memimg7 = params.get('memimg7');
    const mem8 = params.get('mem8');
    const memimg8 = params.get('memimg8');
    const aboutstf = params.get('aboutstf');
    const aboutser = params.get('aboutser');

    document.getElementById('rtopbar1').innerHTML = topbar1;
    document.getElementById('r-title').innerHTML = title;
    document.getElementById('rtopbar2').innerHTML = "<i class=\"fa fa-phone\"></i>" + topbar2;
    document.getElementById('r-logoimg').src = "images/" + logoimg;

    document.getElementById('r-headtxt').innerHTML = topbar1;
    document.getElementById('r-headimg').src = "images/" + headimg;
    document.getElementById('r-about').innerHTML = about;

    document.getElementById('r-revs1_1').innerHTML = revs1_1;
    document.getElementById('r-revs1_2').innerHTML = revs1_2;
    
    document.getElementById('r-food1').innerHTML = food1;
    document.getElementById('r-food2').innerHTML = food2;
    document.getElementById('r-food3').innerHTML = food3;
    document.getElementById('r-food4').innerHTML = food4;

    document.getElementById('r-menu1').src = "images/" + menu1;
    document.getElementById('r-mtext1').innerHTML = mtext1;
    document.getElementById('r-menu2').src = "images/" + menu2;
    document.getElementById('r-mtext2').innerHTML = mtext2;
    document.getElementById('r-menu3').src = "images/" + menu3;
    document.getElementById('r-mtext3').innerHTML = mtext3;
    document.getElementById('r-menu4').src = "images/" + menu4;
    document.getElementById('r-mtext4').innerHTML = mtext4;
    document.getElementById('r-smenu1').innerHTML = mtext1 + "<span>₹" + mprice1 + "</span>";
    document.getElementById('r-smenu2').innerHTML = mtext2 + "<span>₹" + mprice2 + "</span>";
    document.getElementById('r-smenu3').innerHTML = mtext3 + "<span>₹" + mprice3 + "</span>";
    document.getElementById('r-smenu4').innerHTML = mtext4 + "<span>₹" + mprice4 + "</span>";

    document.getElementById('r-cap1').innerHTML = food1;
    document.getElementById('r-cap2').innerHTML = food2;
    document.getElementById('r-cap3').innerHTML = food3;
    document.getElementById('r-cap4').innerHTML = food4;
    document.getElementById('r-image1_1').src = "images/" + image1;
    document.getElementById('r-image1_2').href = "images/" + image1;
    document.getElementById('r-image2_1').src = "images/" + image2;
    document.getElementById('r-image2_2').href = "images/" + image2;
    document.getElementById('r-image3_1').src = "images/" + image3;
    document.getElementById('r-image3_2').href = "images/" + image3;
    document.getElementById('r-image4_1').src = "images/" + image4;
    document.getElementById('r-image4_2').href = "images/" + image4;
    document.getElementById('r-image5_1').src = "images/" + image5;
    document.getElementById('r-image5_2').href = "images/" + image5;
    document.getElementById('r-image6_1').src = "images/" + image6;
    document.getElementById('r-image6_2').href = "images/" + image6;
    document.getElementById('r-image7_1').src = "images/" + image7;
    document.getElementById('r-image7_2').href = "images/" + image7;
    document.getElementById('r-image8_1').src = "images/" + image8;
    document.getElementById('r-image8_2').href = "images/" + image8;

    document.getElementById('r-memimg1').src = "images/" + memimg1;
    document.getElementById('r-mem1').innerHTML = mem1;
    document.getElementById('r-memimg2').src = "images/" + memimg2;
    document.getElementById('r-mem2').innerHTML = mem2;
    document.getElementById('r-memimg3').src = "images/" + memimg3;
    document.getElementById('r-mem3').innerHTML = mem3;
    document.getElementById('r-memimg4').src = "images/" + memimg4;
    document.getElementById('r-mem4').innerHTML = mem4;
    document.getElementById('r-memimg5').src = "images/" + memimg5;
    document.getElementById('r-mem5').innerHTML = mem5;
    document.getElementById('r-memimg6').src = "images/" + memimg6;
    document.getElementById('r-mem6').innerHTML = mem6;
    document.getElementById('r-memimg7').src = "images/" + memimg7;
    document.getElementById('r-mem7').innerHTML = mem7;
    document.getElementById('r-memimg8').src = "images/" + memimg8;
    document.getElementById('r-mem8').innerHTML = mem8;

    document.getElementById('r-aboutstf').innerHTML = aboutstf;
    document.getElementById('r-aboutser').innerHTML = aboutser;

    document.getElementById('r-copy').innerHTML = "Copyright &copy; " + title + ". All Right Reserved.";
});

onload = (event) => {};